
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# (see https://jekyllrb.com/docs/data-files/) for data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Veru's Log"
author:
  name: Veru
  bio: "My Security Record"
  email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about security, technology, and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ver-uu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ver-uu
instagram_username:  your_instagram

# Build settings
markdown: kramdown
theme: null # We are building our own theme
plugins:
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Comments
# Configure comments to be used on post pages
comments:
  provider: "giscus" # or "utterances"

  giscus:
    repo: "ver-uu/ver-uu.github.io" # Replace with your repo
    repo_id: "" # Find this in the Giscus setup, e.g., R_kgDOMfA1_w
    category: "" # e.g., "Announcements"
    category_id: "" # e.g., DIC_kwDOMfA1_84Cf2s-
    mapping: "pathname" # Or "url", "title", etc.
    reactions_enabled: "1"
    emit_metadata: "0"
    theme: "preferred_color_scheme" # or "light", "dark"

  utterances:
    repo: "ver-uu/ver-uu.github.io" # Replace with your repo
    theme: "github-light" # or "github-dark"
    issue_term: "pathname"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the 'exclude:' key here will be automatically added to
# the internal list.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the 'include:' list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
